export enum TOPICS {
  ORDER_SERVICE = 'ORDER_SERVICE',
  PAYMENT_SERVICE = 'PAYMENT_SERVICE',
  NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE',
}

export enum EVENTS {
  ORDER_CREATED = 'ORDER_CREATED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
}
